### ISSUE TITLE
"s3s3mirror.sh": executable file not found in $PATH

### ISSUE THREAD

**Issue by peterlozano** [pmoust/s3s3mirror-docker#4]
I'm getting this error when trying to run the container.

`FATA[0000] Error response from daemon: Cannot start container c78b70fdceb06185b4b62388da4da037a8d9f0994d894cb2ca3f87d684afe56d: [8] System error: exec: "s3s3mirror.sh": executable file not found in $PATH`

**Comment by pmoust** [comment]
@peterlozano fixed in 75e425d
